language: python
python:
  - "2.7"
  - "3.5"

sudo: false

# Cache miniconda installation
cache:
  directories:
    - .miniconda


stages:
  - Lint check
  - Setup
  - test
#  - deploy


before_install:
  - export PATH=".miniconda/bin:$PATH"
  - hash -r

install:
  # Useful for debugging any issues with conda
  - ls -all .miniconda
  - ls -all .miniconda/bin
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy
  - source activate test-environment
  - python setup.py install
  - pip install --upgrade pytest codecov pytest-cov

script:
  - py.test --cov check_auto_deploy --cov-report term-missing

after_success:
  # Ignore codecov failures as the codecov server is not
  # very reliable but we don't want travis to report a failure
  # in the github UI just because the coverage report failed to
  # be published.
  - codecov || echo "codecov upload failed"


# PyPI Deployment: https://docs.travis-ci.com/user/deployment/pypi/
deploy:
  provider: pypi
  user: $PYPI_USER
  # If password contains non alphanumeric characters
  # https://github.com/travis-ci/dpl/issues/377
  # pass it as secured variable
  password: $PYPI_TOKEN
  # otherwise, follow "How to encrypt the password": https://docs.travis-ci.com/user/encryption-keys/
  # `travis encrypt deploy.password="password"`
  #  secure: "secured_password"

  # For debug purposes -> deploy on test.pypi
  server: https://test.pypi.org/legacy/

  skip_cleanup: true
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    python: "3.5"


jobs:
  include:
    - stage: Lint check
      python: "2.7"
      before_install: # Nothing to do
      install: pip install flake8
      script: flake8
      after_success: # Nothing to do

    - stage: Setup
      install:
      - sudo apt-get update
      - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      - bash miniconda.sh -b -u -p .miniconda
      - export PATH=".miniconda/bin:$PATH"
      - hash -r
      - conda config --set always_yes yes --set changeps1 no
      - conda update -q conda
      # "script" should launch something otherwise build fails
      script:
      - conda info -a
      - ls -all .miniconda
      - ls -all .miniconda/bin

      after_success: # Nothing to do



#    - stage: deploy
#      python: "3.5"
#      install:
#        # Minimal install : ignite and dependencies just to build the docs
#        - pip install -r docs/requirements.txt
#        - pip install http://download.pytorch.org/whl/cpu/torch-0.4.1-cp35-cp35m-linux_x86_64.whl
#        # `pip install .` vs `python setup.py install` : 1st works better to produce _module/ignite with source links
#        - pip install .
