#!/bin/bash

set -e # exit on error
set -x # echo commands

# https://conda.io/docs/user-guide/tasks/build-packages/install-conda-build.html
conda install -y conda-build conda-verify anaconda-client

conda config --set anaconda_upload no

# We build a generic noarch python package:
conda build --quiet --no-test --output-folder conda_build conda.recipe

# Convert to other platforms: OSX, WIN
conda convert --platform win-64 conda_build/linux-64/*.tar.bz2 -o conda_build/
conda convert --platform osx-64 conda_build/linux-64/*.tar.bz2 -o conda_build/

# Upload to Anaconda
ls conda_build/*/*.tar.bz2 | xargs -I {} anaconda upload {} -u $ANACONDA_USER -t $ANACONDA_TOKEN
